In [2]:
import pandas as pd
from transformers import RobertaTokenizer, RobertaConfig, RobertaModel
import torch
import torch.nn as nn
import numpy as np

In [3]:
df=pd.read_csv('codegit.csv')

In [4]:
df

Unnamed: 0                                               code  \
0                0  def train(train_dir, model_save_path=None, n_n...   
1                1  def predict(X_img_path, knn_clf=None, model_pa...   
2                2  def show_prediction_labels_on_image(img_path, ...   
3                3  def _rect_to_css(rect):\n    """\n    Convert ...   
4                4  def _trim_css_to_bounds(css, image_shape):\n  ...   
...            ...                                                ...   
457456      457456  def show_version(self):\n        """ custom co...   
457457      457457  def check_path_action(self):\n        """ cust...   
457458      457458  def new_user(yaml_path):\n    '''\n    Return ...   
457459      457459  def _AddPropertiesForExtensions(descriptor, cl...   
457460      457460  def _InternalUnpackAny(msg):\n  """Unpacks Any...   

                                                      url  
0       https://github.com/ageitgey/face_recognition/b...  
1       https://github.com/ageitgey/face_recognition/b...  
2       https://github.com/ageitgey/face_recognition/b...  
3       https://github.com/ageitgey/face_recognition/b...  
4       https://github.com/ageitgey/face_recognition/b...  
...                                                   ...  
457456  https://github.com/xnuinside/clifier/blob/3d70...  
457457  https://github.com/xnuinside/clifier/blob/3d70...  
457458  https://github.com/tklovett/PyShirtsIO/blob/ff...  
457459  https://github.com/ibelie/typy/blob/3616845fb9...  
457460  https://github.com/ibelie/typy/blob/3616845fb9...  

[457461 rows x 3 columns]

In [5]:
df = df.drop(columns=["Unnamed: 0"])

In [7]:
df

code  \
0       def train(train_dir, model_save_path=None, n_n...   
1       def predict(X_img_path, knn_clf=None, model_pa...   
2       def show_prediction_labels_on_image(img_path, ...   
3       def _rect_to_css(rect):\n    """\n    Convert ...   
4       def _trim_css_to_bounds(css, image_shape):\n  ...   
...                                                   ...   
457456  def show_version(self):\n        """ custom co...   
457457  def check_path_action(self):\n        """ cust...   
457458  def new_user(yaml_path):\n    '''\n    Return ...   
457459  def _AddPropertiesForExtensions(descriptor, cl...   
457460  def _InternalUnpackAny(msg):\n  """Unpacks Any...   

                                                      url  
0       https://github.com/ageitgey/face_recognition/b...  
1       https://github.com/ageitgey/face_recognition/b...  
2       https://github.com/ageitgey/face_recognition/b...  
3       https://github.com/ageitgey/face_recognition/b...  
4       https://github.com/ageitgey/face_recognition/b...  
...                                                   ...  
457456  https://github.com/xnuinside/clifier/blob/3d70...  
457457  https://github.com/xnuinside/clifier/blob/3d70...  
457458  https://github.com/tklovett/PyShirtsIO/blob/ff...  
457459  https://github.com/ibelie/typy/blob/3616845fb9...  
457460  https://github.com/ibelie/typy/blob/3616845fb9...  

[457461 rows x 2 columns]

In [8]:
tokenizer = RobertaTokenizer.from_pretrained("microsoft/codebert-base")
model = RobertaModel.from_pretrained("./python_model")

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [10]:
model.to(device)

RobertaModel(
  (embeddings): RobertaEmbeddings(
    (word_embeddings): Embedding(50265, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (token_type_embeddings): Embedding(1, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): RobertaEncoder(
    (layer): ModuleList(
      (0): RobertaLayer(
        (attention): RobertaAttention(
          (self): RobertaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): RobertaSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Drop

In [19]:
device

device(type='cuda')

In [14]:
code_concat = vector_space

In [20]:
code_concat.size()

torch.Size([234853, 768])

In [21]:
import gc

In [29]:
for i in range(234853,300000):
    with torch.no_grad():
        new_vec=model(tokenizer(df["code"][i],padding=True, truncation=True,return_tensors='pt')['input_ids'].cuda())[1]
        gc.collect()
        torch.cuda.empty_cache()
        code_concat=torch.cat((code_concat.cuda(),new_vec.cuda()),0)
        gc.collect()
        torch.cuda.empty_cache()
        print(code_concat.size())

torch.Size([234854, 768])


RuntimeError: CUDA out of memory. Tried to allocate 690.00 MiB (GPU 0; 3.00 GiB total capacity; 1.81 GiB already allocated; 0 bytes free; 1.87 GiB reserved in total by PyTorch)

# Test

In [11]:
df["code"][234852]

'def delete(self, reason=\'\'):\n        """Deletes the event chatroom and if necessary the chatroom, too.\n\n        :param reason: reason for the deletion\n        :return: True if the associated chatroom was also\n                 deleted, otherwise False\n        """\n        db.session.delete(self)\n        db.session.flush()\n        if not self.chatroom.events:\n            db.session.delete(self.chatroom)\n            db.session.flush()\n            delete_room(self.chatroom, reason)\n            return True\n        return False'

In [21]:
with torch.no_grad():
    query = "  Deletes the event chatroom and if necessary the chatroom, too."
    query_vec = model(tokenizer(query,return_tensors='pt')['input_ids'].cuda())[1]
    scores=torch.einsum("ab,cb->ac",query_vec.cuda(),code_concat.cuda())
    scores=torch.softmax(scores,-1)
    prediction =torch.argmax(scores)
    print(df['code'][int(prediction)])
#scores

def delete(self, reason=''):
        """Deletes the event chatroom and if necessary the chatroom, too.

        :param reason: reason for the deletion
        :return: True if the associated chatroom was also
                 deleted, otherwise False
        """
        db.session.delete(self)
        db.session.flush()
        if not self.chatroom.events:
            db.session.delete(self.chatroom)
            db.session.flush()
            delete_room(self.chatroom, reason)
            return True
        return False


In [25]:
values ,indices = scores.topk(10)

In [36]:
values = values.tolist()[0]

In [37]:
values

[0.9999678134918213,
 9.499352017883211e-06,
 8.922521374188364e-06,
 6.698330707877176e-06,
 3.159749439873849e-06,
 2.80609719993663e-06,
 2.156397158614709e-07,
 1.5499392702622572e-07,
 1.48923220422148e-07,
 1.1381721520820065e-07]

In [38]:
indices

tensor([[234852, 136263, 126206, 183315,  53058, 136291,  40587, 136323,  42526,
          54777]], device='cuda:0')

# Inference

In [61]:
new_vec = model(tokenizer(df["code"][174],padding=True, truncation=True,return_tensors='pt')['input_ids'])[1]

# Concatenation

In [62]:
code_concat=torch.cat((code_concat,new_vec),0)

# Saving vector space

In [39]:
torch.save(code_concat, 'vector_space_234.pt')

In [13]:
vector_space = torch.load('vector_space_234853.pt')

In [10]:
query = "save as sequence file"
query_vec = model(tokenizer(query,return_tensors='pt')['input_ids'])[1]
scores=torch.einsum("ab,cb->ac",query_vec,vector_space)
scores=torch.softmax(scores,-1)
prediction =torch.argmax(scores)
df['code'][int(prediction)]

'def saveAsSequenceFile(self, path, compressionCodecClass=None):\n        """\n        Output a Python RDD of key-value pairs (of form C{RDD[(K, V)]}) to any Hadoop file\n        system, using the L{org.apache.hadoop.io.Writable} types that we convert from the\n        RDD\'s key and value types. The mechanism is as follows:\n\n            1. Pyrolite is used to convert pickled Python RDD into RDD of Java objects.\n            2. Keys and values of this Java RDD are converted to Writables and written out.\n\n        :param path: path to sequence file\n        :param compressionCodecClass: (None by default)\n        """\n        pickledRDD = self._pickled()\n        self.ctx._jvm.PythonRDD.saveAsSequenceFile(pickledRDD._jrdd, True,\n                                                   path, compressionCodecClass)'

In [56]:
scores

tensor([[8.9883e-05, 6.9719e-02, 1.4829e-04, 3.2514e-08, 1.5014e-04, 3.3651e-11,
         7.3051e-03, 1.0486e-05, 8.4265e-05, 1.9627e-08, 9.9114e-10, 1.7181e-11,
         7.6967e-07, 2.3420e-07, 7.5435e-05, 1.6278e-05, 1.2505e-06, 1.5227e-02,
         3.7393e-07, 1.2441e-04, 3.5281e-07, 4.1157e-04, 3.9695e-07, 2.1586e-05,
         2.2509e-07, 9.9083e-06, 1.1952e-03, 5.1477e-10, 4.5141e-05, 2.5419e-05,
         1.7339e-06, 1.0706e-02, 6.4896e-07, 5.7015e-05, 2.3450e-08, 1.5728e-02,
         1.4556e-02, 1.6688e-04, 3.7909e-02, 6.3608e-04, 1.0445e-05, 1.3230e-06,
         2.7618e-01, 2.2660e-01, 1.2301e-02, 2.0655e-03, 2.3229e-06, 2.9770e-01,
         5.3537e-03, 6.6324e-04, 1.0583e-08, 2.9835e-07, 4.3689e-08, 8.6893e-08,
         7.0633e-04, 3.9256e-06, 5.8707e-07, 2.4961e-08, 3.5754e-08, 3.9828e-03]],
       grad_fn=<SoftmaxBackward>)

In [123]:
code_concat

tensor([[-0.0396,  0.0321, -0.1320,  ...,  0.1742, -0.2643,  0.3543],
        [ 0.1358, -0.3192,  0.1960,  ..., -0.1715,  0.1855,  0.5175],
        [-0.2785,  0.4911,  0.2407,  ..., -0.1964,  0.3436,  0.1469],
        ...,
        [-0.0553, -0.0858, -0.1548,  ..., -0.4652,  0.4013,  0.0755],
        [ 0.1154, -0.4007, -0.2057,  ...,  0.3505, -0.2217,  0.5642],
        [ 0.4179, -0.4487, -0.6455,  ..., -0.0456,  0.4984,  0.2423]],
       grad_fn=<CatBackward>)

In [82]:
torch.cuda.empty_cache()

In [11]:
import gc

gc.collect()

494

In [81]:
gc.collect()
torch.cuda.empty_cache()

15

In [76]:
gc.collect()

15

In [1]:
test = [1,2,3]
my_list = sorted(test, reverse=True)
my_list

[3, 2, 1]